"""``openbase`` — the Openbase Cloud CLI entry point.

A Heroku-style client for the Openbase PaaS: log in once, then read your apps'
logs, status, config, and releases from the terminal. It speaks only HTTPS to
the Openbase Cloud API and needs no cloud credentials.
"""

from __future__ import annotations

import click

from openbase_cli.commands.apps_commands import apps, open_app
from openbase_cli.commands.auth_commands import login, logout, whoami
from openbase_cli.commands.config_commands import config as config_cmd
from openbase_cli.commands.logs_commands import logs
from openbase_cli.commands.ps_commands import ps, status
from openbase_cli.commands.releases_commands import releases

try:
    from openbase_cli._version import __version__
except ImportError:  # pragma: no cover - generated by hatch-vcs in built wheels
    __version__ = "0+unknown"


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(__version__, "-V", "--version", prog_name="openbase")
def main() -> None:
    """Openbase Cloud CLI.

    Examples:

      openbase login

      openbase apps

      openbase logs -a my-app --tail

      openbase config -a my-app
    """


# Auth
main.add_command(login)
main.add_command(logout)
main.add_command(whoami)

# Apps
main.add_command(apps)
main.add_command(open_app)

# Operations
main.add_command(logs)
main.add_command(ps)
main.add_command(status)
main.add_command(config_cmd)
main.add_command(releases)


if __name__ == "__main__":
    main()
