"""``openbase`` — the Openbase Cloud CLI entry point.

A Heroku-style client for the Openbase Cloud PaaS and an alternative to the web
dashboard: sign in once, then read your apps, logs, config, releases, usage,
projects, and workspaces from the terminal. It speaks only HTTPS to the
Openbase Cloud API. Login and devspace/agent features are delegated to the
separate ``openbase-coder`` CLI.
"""

from __future__ import annotations

import click

from openbase_cli.commands.account_commands import account
from openbase_cli.commands.apps_commands import apps, open_app
from openbase_cli.commands.auth_commands import coder, login, logout, whoami
from openbase_cli.commands.config_commands import config as config_cmd
from openbase_cli.commands.health_commands import health_check
from openbase_cli.commands.logs_commands import logs
from openbase_cli.commands.project_commands import projects
from openbase_cli.commands.ps_commands import ps, status
from openbase_cli.commands.releases_commands import releases
from openbase_cli.commands.usage_commands import usage
from openbase_cli.commands.workspace_commands import workspaces

try:
    from openbase_cli._version import __version__
except ImportError:  # pragma: no cover - generated by hatch-vcs in built wheels
    __version__ = "0+unknown"


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(__version__, "-V", "--version", prog_name="openbase")
def main() -> None:
    """Openbase Cloud CLI.

    Examples:

      openbase login

      openbase apps

      openbase logs -a my-app --tail

      openbase usage

      openbase coder devspaces status
    """


# Auth (login/coder delegate to the openbase-coder executable)
main.add_command(login)
main.add_command(logout)
main.add_command(whoami)
main.add_command(account)
main.add_command(coder)

# Apps / deploys
main.add_command(apps)
main.add_command(open_app)
main.add_command(logs)
main.add_command(ps)
main.add_command(status)
main.add_command(config_cmd)
main.add_command(health_check)
main.add_command(releases)

# Account-wide resources
main.add_command(usage)
main.add_command(projects)
main.add_command(workspaces)


if __name__ == "__main__":
    main()
